"""crear tablas de auth y workspace

Revision ID: cd5cb06eb146
Revises: 
Create Date: 2026-09-14 15:48:52.347365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd5cb06eb146'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('perfiles',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado_lienzo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id_dueno', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_dueno'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colaboradores',
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Enum('LECTOR', 'EDITOR', name='rol_colaborador'), nullable=False),
    sa.Column('unido_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_proyecto', 'id_usuario')
    )
    op.create_table('historial_versiones',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('snapshot_lienzo', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes_chat',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensajes_chat')
    op.drop_table('historial_versiones')
    op.drop_table('colaboradores')
    op.drop_table('proyectos')
    op.drop_table('perfiles')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
