"""tabla configuraciones de transpilacion

Revision ID: ea1fb0d3dea4
Revises: 7c240422817d
Create Date: 2026-09-16 18:43:25.415190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1fb0d3dea4'
down_revision: Union[str, None] = '7c240422817d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuraciones_transpilacion',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=150), nullable=False),
    sa.Column('artifact_id', sa.String(length=100), nullable=False),
    sa.Column('java_version', sa.String(length=10), nullable=False),
    sa.Column('spring_boot_version', sa.String(length=20), nullable=False),
    sa.Column('base_datos', sa.Enum('POSTGRESQL', 'MYSQL', 'H2', name='base_datos_destino'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_proyecto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuraciones_transpilacion')
    # ### end Alembic commands ###
